config/routes.rb
Rails.application.routes.draw do
  # get 'students/new'
  # get 'students/index'
  # get 'students/show'
  # get 'students/edit'
  # get 'students/update'
  # get 'students/delete'
  # get 'students/destroy'
  # get 'students/create'
  # get 'instructors/new'
  # get 'instructors/index'
  # get 'instructors/show'
  # get 'instructors/edit'
  # get 'instructors/update'
  # get 'instructors/delete'
  # get 'instructors/destroy'
  # get 'instructors/create'
  # get 'courses/new'
  # get 'courses/index'
  # get 'courses/show'
  # get 'courses/edit'
  # get 'courses/update'
  # get 'courses/delete'
  # get 'courses/destroy'
  # get 'courses/create'
  # get 'cohorts/new'
  # get 'cohorts/index'
  # get 'cohorts/show'
  # get 'cohorts/edit'
  # get 'cohorts/update'
  # get 'cohorts/delete'
  # get 'cohorts/destroy'
  # get 'cohorts/create'
  resources :students
  resources :instructors
  resources :cohorts
  resources :courses

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # ----- add these lines here: -----

	# Add a root route if you don't have one...
	# We can use users#new for now, or replace this with the controller and action you want to be the site root:
	root to: 'users#new'
  	
  # sign up page with form:
get 'users/new' => 'users#new', as: :new_user

# create (post) action for when sign up form is submitted:
post 'users' => 'users#create'
# log in page with form:
get '/login'     => 'sessions#new'
	
# create (post) action for when log in form is submitted:
post '/login'    => 'sessions#create'

# delete action to log out:
delete '/logout' => 'sessions#destroy'  
  
end

app/models/cohort.rb
class Cohort < ApplicationRecord
    belongs_to :course
    has_many :students
    has_one :instructor
    belongs_to :student
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  def new
    @cohort = Cohort.new
  end

  def index
    @cohorts = Cohort.all
  end

  def show
    @cohort = Cohort.find(params[:id])
  end

  def edit
    @cohort = Cohort.find(params[:id])
  end

  def update
      # loads the user with id of params[:id]
    #   from the database
    cohort = Cohort.find(params[:id])

    # updates the user that was currently loaded
    #   with the information retrieved from the
    #   form

    # user.update(
    #   username: params[:user][:username],
    #   password: params[:user][:password]
    # )
    cohort.update(user_params)

    # goes to show page
    redirect_to cohort_path(user)
  end

  def delete
  
  end

  def destroy
    # this loads the user first
    cohort = Cohort.find(params[:id])

    # this uses the information inside the user
    #   object and deletes the user
    cohort.destroy
    # User.destroy(params[:id])

    redirect_to cohorts_path
  end
    
  def create
    @cohort = Cohort.new(cohort_params)
    @cohort.save

  respond_to do |format|
    # redirects to the '/users' path
    format.html { redirect_to cohorts_path }
    format.js { render '/cohorts/create.js.erb' }
  end
end
def cohort_params
  # strong parameters - whitelist of allowed fields #=> permit(:name, :email, ...)
  # that can be submitted by a form to the user model #=> require(:user)
  params.require(:cohort).permit(:name, :startdate, :enddate, :course_id)
  
end
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/views/cohorts/create.html.erb
<h1>Cohorts#create</h1>
<p>Find me in app/views/cohorts/create.html.erb</p>

app/views/cohorts/delete.html.erb
<h1>Cohorts#delete</h1>
<p>Find me in app/views/cohorts/delete.html.erb</p>

app/views/cohorts/destroy.html.erb
<h1>Cohorts#destroy</h1>
<p>Find me in app/views/cohorts/destroy.html.erb</p>

app/views/cohorts/edit.html.erb
<h1>Cohorts#edit</h1>
<p>Find me in app/views/cohorts/edit.html.erb</p>

app/views/cohorts/index.html.erb
<div class="container">
    <h5>Cohorts</h5>
    <p>These are the cohorts</p>
    
<table class="centered">
        <thead>
          <tr>
              <th>Name</th>
              <th>Total Hours</th>
              <th>Created at</th>
          </tr>
        </thead>
        <%@cohorts.each do |cohort|%>
            <tbody>
                <tr>
                    <td><%=cohort.name%></td>
                    <td><%=cohort.startdate%></td>
                    <td><%=cohort.enddate%></td>
                    <th><%= link_to "Show ", cohort_path(cohort) %> </th>
                    <th><%= link_to "Edit ", edit_cohort_path(cohort) %> </th>
                    <th><%= link_to "Destroy ", cohort_path(cohort), method: :delete %> </th>
                </tr>
        <%end%>
          
        </tbody>
      </table>
    </div>

    <a href="/cohorts/new">Add Cohorts</a>

app/views/cohorts/new.html.erb
 <%=form_for @cohort, method: :post, local: true do |form| %>
  name<%= form.text_field :name %>
  Startdate<%= form.date_field :startdate %>
  Enddate<%= form.date_field :enddate%>
  <%= form.text_field :course_id, value: @course_id %>
  <%= form.submit "create"%>
<% end %>

app/views/cohorts/show.html.erb
<h1>Cohorts#show</h1>
<p>Find me in app/views/cohorts/show.html.erb</p>

app/views/cohorts/update.html.erb
<h1>Cohorts#update</h1>
<p>Find me in app/views/cohorts/update.html.erb</p>