config/routes.rb
Rails.application.routes.draw do
  # get 'students/new'
  # get 'students/index'
  # get 'students/show'
  # get 'students/edit'
  # get 'students/update'
  # get 'students/delete'
  # get 'students/destroy'
  # get 'students/create'
  # get 'instructors/new'
  # get 'instructors/index'
  # get 'instructors/show'
  # get 'instructors/edit'
  # get 'instructors/update'
  # get 'instructors/delete'
  # get 'instructors/destroy'
  # get 'instructors/create'
  # get 'courses/new'
  # get 'courses/index'
  # get 'courses/show'
  # get 'courses/edit'
  # get 'courses/update'
  # get 'courses/delete'
  # get 'courses/destroy'
  # get 'courses/create'
  # get 'cohorts/new'
  # get 'cohorts/index'
  # get 'cohorts/show'
  # get 'cohorts/edit'
  # get 'cohorts/update'
  # get 'cohorts/delete'
  # get 'cohorts/destroy'
  # get 'cohorts/create'
  resources :students
  resources :instructors
  resources :cohorts
  resources :courses

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # ----- add these lines here: -----

	# Add a root route if you don't have one...
	# We can use users#new for now, or replace this with the controller and action you want to be the site root:
	root to: 'users#new'
  	
  # sign up page with form:
get 'users/new' => 'users#new', as: :new_user

# create (post) action for when sign up form is submitted:
post 'users' => 'users#create'
# log in page with form:
get '/login'     => 'sessions#new'
	
# create (post) action for when log in form is submitted:
post '/login'    => 'sessions#create'

# delete action to log out:
delete '/logout' => 'sessions#destroy'  
  
end

app/models/student.rb
class Student < ApplicationRecord
    belongs_to :cohort
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new
    @student = Student.new
  end

  def create
    acohort = cohortall().find_by(name: params[:student][:cohort])
   
    
      Student.create(
        firstname: params[:student][:firstname],
        lastname: params[:student][:lastname],
        age: params[:student][:age],
        educationlevel: params[:student][:educationlevel]
      )
      redirect_to student_path

#  respond_to do |format|
#       # redirects to the '/users' path
#       format.html { redirect_to '/students/index.html.erb' }
#       format.js { render '/students/create.js.erb' }
#     end
  end

  def index
    @students = Student.all

    respond_to do |format|
      format.html { render '/students/index.html.erb' }
      format.js { render '/students/index.js.erb' }
      format.json { render json: @students }
    end
  end

  def show
    @student = Student.find(params[:id])
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
      # loads the user with id of params[:id]
    #   from the database
    student = Student.find(params[:id])

    # updates the user that was currently loaded
    #   with the information retrieved from the
    #   form

    # user.update(
    #   username: params[:user][:username],
    #   password: params[:user][:password]
    # )
    student.update(student_params)

    # goes to show page
    redirect_to students_show_path(student)
  end

  def delete
    
  end

  def destroy
    # this loads the user first
    student = Student.find(params[:id])

    # this uses the information inside the user
    #   object and deletes the user
    student.destroy
    # User.destroy(params[:id])
    
    redirect_to students_index_path
  end

  private

  # def student_params
  #   params.require(:student).permit(:firstname, :lastname, :age, :cohort, :educationlevel)
  # end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/create.html.erb
<h1>Students#create</h1>
<p>Find me in app/views/students/create.html.erb</p>

app/views/students/delete.html.erb
<h1>Students#delete</h1>
<p>Find me in app/views/students/delete.html.erb</p>

app/views/students/destroy.html.erb
<h1>Students#destroy</h1>
<p>Find me in app/views/students/destroy.html.erb</p>

app/views/students/edit.html.erb
<h1>Students#edit</h1>
<p>Find me in app/views/students/edit.html.erb</p>

app/views/students/index.html.erb
 <div class="container">
    <h5>Students</h5>
    <p>These are all our students</p>
    
<table class="centered">
        <thead>
          <tr>
              <th>FirstName</th>
              <th>LastName</th>
              <th>Education Level</th>
              <th>Delete</th>
              <th>Edit</th>
          </tr>
        </thead>
        <%@students.each do |student|%>
            <tbody>
                <tr>
                    <td><%=student.firstname%></td>
                    <td><%=student.lastname%></td>
                    <td><%=student.educationlevel%></td>
                    <th><%= link_to "Show ", student_path(student) %> </th>
                    <th><%= link_to "Edit ", edit_student_path(student) %> </th>
                    <th><%= link_to "Destroy ", student_path(student), method: :delete %> </th>
                </tr>
        <%end%>
          
        </tbody>
      </table>
    </div>
    <br>
   <a href="/students/new">Add Student</a>
          
         

app/views/students/new.html.erb
<%=form_for @student, method: :post, local: true do |form| %>
  Firstname<%= form.text_field :firstname %>
  Lastname<%= form.text_field :lastname %>
  Age <%= form.number_field :age %>
  Educationlevel <%= form.text_field :educationlevel%>
  <%=form.submit %>
<% end %>

app/views/students/show.html.erb
<h1>Students#show</h1>
<p>Find me in app/views/students/show.html.erb</p>

app/views/students/update.html.erb
<h1>Students#update</h1>
<p>Find me in app/views/students/update.html.erb</p>