config/routes.rb
Rails.application.routes.draw do
  # get 'students/new'
  # get 'students/index'
  # get 'students/show'
  # get 'students/edit'
  # get 'students/update'
  # get 'students/delete'
  # get 'students/destroy'
  # get 'students/create'
  # get 'instructors/new'
  # get 'instructors/index'
  # get 'instructors/show'
  # get 'instructors/edit'
  # get 'instructors/update'
  # get 'instructors/delete'
  # get 'instructors/destroy'
  # get 'instructors/create'
  # get 'courses/new'
  # get 'courses/index'
  # get 'courses/show'
  # get 'courses/edit'
  # get 'courses/update'
  # get 'courses/delete'
  # get 'courses/destroy'
  # get 'courses/create'
  # get 'cohorts/new'
  # get 'cohorts/index'
  # get 'cohorts/show'
  # get 'cohorts/edit'
  # get 'cohorts/update'
  # get 'cohorts/delete'
  # get 'cohorts/destroy'
  # get 'cohorts/create'
  resources :students
  resources :instructors
  resources :cohorts
  resources :courses

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # ----- add these lines here: -----

	# Add a root route if you don't have one...
	# We can use users#new for now, or replace this with the controller and action you want to be the site root:
	root to: 'users#new'
  	
  # sign up page with form:
get 'users/new' => 'users#new', as: :new_user

# create (post) action for when sign up form is submitted:
post 'users' => 'users#create'
# log in page with form:
get '/login'     => 'sessions#new'
	
# create (post) action for when log in form is submitted:
post '/login'    => 'sessions#create'

# delete action to log out:
delete '/logout' => 'sessions#destroy'  
  
end

app/models/instructor.rb
class Instructor < ApplicationRecord
    belongs_to :cohort
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  def new
    @instructor = Instructor.new
  end

  def create
    acohort = cohortall().find_by(name: params[:instructor][:cohort])
   
    Instructor.create(
      firstname: params[:instructor][:firstname],
      lastname: params[:instructor][:lastname],
      age: params[:instructor][:age],
      educationlevel: params[:instructor][:educationlevel],
      salary: params[:instructor][:salary],
      cohort: acohort.id
    )

    respond_to do |format|
      # redirects to the '/users' path
      format.html { redirect_to instructors_path }
      format.js { render '/instructors/create.js.erb' }
    end
  end

  def index
    @instructors = Instructor.all

    respond_to do |format|
      format.html { render '/instructors/index.html.erb' }
      format.js { render '/instructors/index.js.erb' }
      format.json { render json: @instructors }
    end
  end

  def show
    @instructor = Instructor.find(params[:id])
  end

  def edit
    @instructor = Instructor.find(params[:id])
  end

  def update
      # loads the user with id of params[:id]
    #   from the database
    instructor = Instructor.find(params[:id])

    # updates the user that was currently loaded
    #   with the information retrieved from the
    #   form

    # user.update(
    #   username: params[:user][:username],
    #   password: params[:user][:password]
    # )
    instructor.update(instructor_params)

    # goes to show page
    redirect_to instructor_path(instructor)
  end

  def delete
    
  end

  def destroy
    # this loads the user first
    instructor = Instructor.find(params[:id])

    # this uses the information inside the user
    #   object and deletes the user
    instructor.destroy
    # User.destroy(params[:id])
    
    redirect_to instructors_path
  end

  private

  # def instructor_params
  #   params.require(:instructor).permit(:username, :password, :password_confirmation)
  # end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/create.html.erb
<h1>Instructors#create</h1>
<p>Find me in app/views/instructors/create.html.erb</p>

app/views/instructors/delete.html.erb
<h1>Instructors#delete</h1>
<p>Find me in app/views/instructors/delete.html.erb</p>

app/views/instructors/destroy.html.erb
<h1>Instructors#destroy</h1>
<p>Find me in app/views/instructors/destroy.html.erb</p>

app/views/instructors/edit.html.erb
<h1>Instructors#edit</h1>
<p>Find me in app/views/instructors/edit.html.erb</p>

app/views/instructors/index.html.erb
 <div class="container">
    <h5>Instructors</h5>
    <p>These are all our instructors</p>
    
<table class="centered">
        <thead>
          <tr>
              <th>FirstName</th>
              <th>LastName</th>
              <th>Education Level</th>
              <th>Delete</th>
              <th>Edit</th>
          </tr>
        </thead>
        <%@instructors.each do |instructor|%>
            <tbody>
                <tr>
                    <td><%=instrucor.firstname%></td>
                    <td><%=instructor.lastname%></td>
                    <td><%=instructor.educationlevel%></td>
                    <th><%= link_to "Show ", instructor_path(instrucor) %> </th>
                    <th><%= link_to "Edit ", edit_instructor_path(instrucor) %> </th>
                    <th><%= link_to "Destroy ", instructor_path(instrucor), method: :delete %> </th>
                </tr>
        <%end%>
          
        </tbody>
      </table>
    </div>
    <a href="/instructors/new">Add Instructors</a>

app/views/instructors/new.html.erb
<%=form_for @instructor, method: :post, local: true do |form| %>
  Firstname<%= form.text_field :firstname %>
  Lastname<%= form.text_field :lastname %>
  Age <%= form.number_field :age %>
  Educationlevel <%= form.text_field :educationlevel%>
  Salary <%= form.text_field :salary%>
  cohort <%= form.text_field :cohort%>
  <%=form.submit %>
<% end %>

app/views/instructors/show.html.erb
<h1>Instructors#show</h1>
<p>Find me in app/views/instructors/show.html.erb</p>

app/views/instructors/update.html.erb
<h1>Instructors#update</h1>
<p>Find me in app/views/instructors/update.html.erb</p>